name: Bug Report
description: Report broken or incorrect behaviour
labels: ["bug", "pending"]
assignees: 
  - konradsic

body:
  - type: markdown
    attributes:
      value: >
        Thanks for submitting a bug report, your issue will be considered by the library developers.
        
        **Note:** This form is for bugs only!
  - type: input
    id: description
    attributes:
      label: Description
      description: A short and concise description of the bug
      placeholder: e.g. When I try to do ... an error occurs
    validations:
      required: true
  - type: dropdown
    id: problem-related-to
    attributes:
      label: To what part of the library the bug is related?
      description: Please specify
      options:
        - The core library
        - API Interface
        - Weather Client
        - The documentation
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: What did you do that the bug occured
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Minimal reproducible code
      description: Please paste the code where the bug occured
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      description: Please describe what results you've expected
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual results
      description: Please describe what actually happened (instead of expected behaviour)
    validations:
      required: true
  - type: input
    id: py-version
    attributes:
      label: Python version
      description: Please specity your Python version
      placeholder: e.g. 3.10
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add anything related to bug that can help resolve it (e.g. screenshots)
      placeholder: If you want to send a large block of code consider using a site like pastebin
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure to fullfill all requirements in the boxes before submitting the issue
      options:
        - label: I use the latest relase of the library
          required: true
        - label: I've searched open issues for duplicate and similiar bugs
          required: true
        - label: I've hidden the WeatherAPI token if needed
          required: true
        - label: I agree to conributing rules and Code of Conduct
          required: true
