name: build

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pkg-and-docs-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11' ]
        language: [ 'en' ]

    name: package & docs (${{ matrix.python-version }}/${{ matrix.language }})
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3.1.3
        with:
         python-version: ${{ matrix.python-version }}
         
      - name: Install requirements
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
          
      - name: Build and install package
        run: |
          python3 ./setup.py build
          python3 ./setup.py install
          
      - name: Build docs
        shell: bash
        run: |
          pip install sphinx==5.3.0 sphinx-book-theme==1.0.1
          cd docs
          sphinx-build -b html source build
